

package org.jetbrains.kotlin.formver.plugin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.formver.plugin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("formver.compiler-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class PhasedDiagnosticTestGenerated extends AbstractPhasedDiagnosticTest {
  private void run(java.lang.String fileName) {
    runTest("formver.compiler-plugin/testData/diagnostics/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("formver.compiler-plugin/testData/diagnostics/expensive_verification")
  @TestDataPath("$PROJECT_ROOT")
  public class Expensive_verification {
    private void run(java.lang.String fileName) {
      runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/" + fileName);
    }

    @Test
    public void testAllFilesPresentInExpensive_verification() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/expensive_verification"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("backing_field_getters.kt")
    public void testBacking_field_getters() {
      run("backing_field_getters.kt");
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms")
    @TestDataPath("$PROJECT_ROOT")
    public class Algorithms {
      private void run(java.lang.String fileName) {
        runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms/" + fileName);
      }

      @Test
      public void testAllFilesPresentInAlgorithms() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("binary_search.kt")
      public void testBinary_search() {
        run("binary_search.kt");
      }

      @Test
      @TestMetadata("max_character.kt")
      public void testMax_character() {
        run("max_character.kt");
      }

      @Test
      @TestMetadata("merge_sort_of_string.kt")
      public void testMerge_sort_of_string() {
        run("merge_sort_of_string.kt");
      }

      @Test
      @TestMetadata("quick_sort_of_string.kt")
      public void testQuick_sort_of_string() {
        run("quick_sort_of_string.kt");
      }

      @Test
      @TestMetadata("z_function.kt")
      public void testZ_function() {
        run("z_function.kt");
      }
    }
  }

  @Nested
  @TestMetadata("formver.compiler-plugin/testData/diagnostics/stdlib")
  @TestDataPath("$PROJECT_ROOT")
  public class Stdlib {
    private void run(java.lang.String fileName) {
      runTest("formver.compiler-plugin/testData/diagnostics/stdlib/" + fileName);
    }

    @Test
    public void testAllFilesPresentInStdlib() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/stdlib"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("stdlib_replacement_tests.kt")
    public void testStdlib_replacement_tests() {
      run("stdlib_replacement_tests.kt");
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/stdlib/list")
    @TestDataPath("$PROJECT_ROOT")
    public class List {
      private void run(java.lang.String fileName) {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/list/" + fileName);
      }

      @Test
      public void testAllFilesPresentInList() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/stdlib/list"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("binary_search.kt")
      public void testBinary_search() {
        run("binary_search.kt");
      }

      @Test
      @TestMetadata("custom_list.kt")
      public void testCustom_list() {
        run("custom_list.kt");
      }

      @Test
      @TestMetadata("list.kt")
      public void testList() {
        run("list.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/stdlib/string")
    @TestDataPath("$PROJECT_ROOT")
    public class String {
      private void run(java.lang.String fileName) {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/string/" + fileName);
      }

      @Test
      public void testAllFilesPresentInString() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/stdlib/string"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("chars.kt")
      public void testChars() {
        run("chars.kt");
      }

      @Test
      @TestMetadata("strings.kt")
      public void testStrings() {
        run("strings.kt");
      }
    }
  }

  @Nested
  @TestMetadata("formver.compiler-plugin/testData/diagnostics/uniqueness_checker")
  @TestDataPath("$PROJECT_ROOT")
  public class Uniqueness_checker {
    private void run(java.lang.String fileName) {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/" + fileName);
    }

    @Test
    @TestMetadata("aliasing.kt")
    public void testAliasing() {
      run("aliasing.kt");
    }

    @Test
    public void testAllFilesPresentInUniqueness_checker() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/uniqueness_checker"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("annotations.kt")
    public void testAnnotations() {
      run("annotations.kt");
    }

    @Test
    @TestMetadata("assign_local.kt")
    public void testAssign_local() {
      run("assign_local.kt");
    }

    @Test
    @TestMetadata("assign_property.kt")
    public void testAssign_property() {
      run("assign_property.kt");
    }

    @Test
    @TestMetadata("break.kt")
    public void testBreak() {
      run("break.kt");
    }

    @Test
    @TestMetadata("call.kt")
    public void testCall() {
      run("call.kt");
    }

    @Test
    @TestMetadata("consistency.kt")
    public void testConsistency() {
      run("consistency.kt");
    }

    @Test
    @TestMetadata("constructor.kt")
    public void testConstructor() {
      run("constructor.kt");
    }

    @Test
    @TestMetadata("context.kt")
    public void testContext() {
      run("context.kt");
    }

    @Test
    @TestMetadata("continue.kt")
    public void testContinue() {
      run("continue.kt");
    }

    @Test
    @TestMetadata("default_argument.kt")
    public void testDefault_argument() {
      run("default_argument.kt");
    }

    @Test
    @TestMetadata("dump_cfg.kt")
    public void testDump_cfg() {
      run("dump_cfg.kt");
    }

    @Test
    @TestMetadata("leak.kt")
    public void testLeak() {
      run("leak.kt");
    }

    @Test
    @TestMetadata("loop.kt")
    public void testLoop() {
      run("loop.kt");
    }

    @Test
    @TestMetadata("nullable.kt")
    public void testNullable() {
      run("nullable.kt");
    }

    @Test
    @TestMetadata("operator.kt")
    public void testOperator() {
      run("operator.kt");
    }

    @Test
    @TestMetadata("primitive.kt")
    public void testPrimitive() {
      run("primitive.kt");
    }

    @Test
    @TestMetadata("receiver.kt")
    public void testReceiver() {
      run("receiver.kt");
    }

    @Test
    @TestMetadata("return.kt")
    public void testReturn() {
      run("return.kt");
    }

    @Test
    @TestMetadata("throw.kt")
    public void testThrow() {
      run("throw.kt");
    }

    @Test
    @TestMetadata("try_catch.kt")
    public void testTry_catch() {
      run("try_catch.kt");
    }

    @Test
    @TestMetadata("when_expression.kt")
    public void testWhen_expression() {
      run("when_expression.kt");
    }
  }

  @Nested
  @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification")
  @TestDataPath("$PROJECT_ROOT")
  public class Verification {
    private void run(java.lang.String fileName) {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/" + fileName);
    }

    @Test
    public void testAllFilesPresentInVerification() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("basic.kt")
    public void testBasic() {
      run("basic.kt");
    }

    @Test
    @TestMetadata("do_not_verify.kt")
    public void testDo_not_verify() {
      run("do_not_verify.kt");
    }

    @Test
    @TestMetadata("extension_properties.kt")
    public void testExtension_properties() {
      run("extension_properties.kt");
    }

    @Test
    @TestMetadata("full_viper_dump.kt")
    public void testFull_viper_dump() {
      run("full_viper_dump.kt");
    }

    @Test
    @TestMetadata("function_object.kt")
    public void testFunction_object() {
      run("function_object.kt");
    }

    @Test
    @TestMetadata("function_overloading.kt")
    public void testFunction_overloading() {
      run("function_overloading.kt");
    }

    @Test
    @TestMetadata("havoc.kt")
    public void testHavoc() {
      run("havoc.kt");
    }

    @Test
    @TestMetadata("manualFolding.kt")
    public void testManualFolding() {
      run("manualFolding.kt");
    }

    @Test
    @TestMetadata("manualFoldingNegative.kt")
    public void testManualFoldingNegative() {
      run("manualFoldingNegative.kt");
    }

    @Test
    @TestMetadata("multiple_receivers.kt")
    public void testMultiple_receivers() {
      run("multiple_receivers.kt");
    }

    @Test
    @TestMetadata("old.kt")
    public void testOld() {
      run("old.kt");
    }

    @Test
    @TestMetadata("shadowing.kt")
    public void testShadowing() {
      run("shadowing.kt");
    }

    @Test
    @TestMetadata("unit_return_type.kt")
    public void testUnit_return_type() {
      run("unit_return_type.kt");
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/classes")
    @TestDataPath("$PROJECT_ROOT")
    public class Classes {
      private void run(java.lang.String fileName) {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/" + fileName);
      }

      @Test
      @TestMetadata("acc_precondition.kt")
      public void testAcc_precondition() {
        run("acc_precondition.kt");
      }

      @Test
      public void testAllFilesPresentInClasses() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/classes"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("inheritance.kt")
      public void testInheritance() {
        run("inheritance.kt");
      }

      @Test
      @TestMetadata("inheritance_fields.kt")
      public void testInheritance_fields() {
        run("inheritance_fields.kt");
      }

      @Test
      @TestMetadata("interfaces.kt")
      public void testInterfaces() {
        run("interfaces.kt");
      }

      @Test
      @TestMetadata("manual_permissions.kt")
      public void testManual_permissions() {
        run("manual_permissions.kt");
      }

      @Test
      @TestMetadata("member_functions.kt")
      public void testMember_functions() {
        run("member_functions.kt");
      }

      @Test
      @TestMetadata("override_properties_types.kt")
      public void testOverride_properties_types() {
        run("override_properties_types.kt");
      }

      @Test
      @TestMetadata("predicates.kt")
      public void testPredicates() {
        run("predicates.kt");
      }

      @Test
      @TestMetadata("predicates_access.kt")
      public void testPredicates_access() {
        run("predicates_access.kt");
      }

      @Test
      @TestMetadata("primary_constructors.kt")
      public void testPrimary_constructors() {
        run("primary_constructors.kt");
      }

      @Test
      @TestMetadata("private_properties.kt")
      public void testPrivate_properties() {
        run("private_properties.kt");
      }

      @Test
      @TestMetadata("property_accessors.kt")
      public void testProperty_accessors() {
        run("property_accessors.kt");
      }

      @Test
      @TestMetadata("secondary_constructors.kt")
      public void testSecondary_constructors() {
        run("secondary_constructors.kt");
      }

      @Test
      @TestMetadata("subtyping.kt")
      public void testSubtyping() {
        run("subtyping.kt");
      }

      @Test
      @TestMetadata("unique_fields.kt")
      public void testUnique_fields() {
        run("unique_fields.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/contracts")
    @TestDataPath("$PROJECT_ROOT")
    public class Contracts {
      private void run(java.lang.String fileName) {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/" + fileName);
      }

      @Test
      public void testAllFilesPresentInContracts() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/contracts"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Nested
      @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative")
      @TestDataPath("$PROJECT_ROOT")
      public class Negative {
        private void run(java.lang.String fileName) {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/" + fileName);
        }

        @Test
        public void testAllFilesPresentInNegative() {
          KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative"), Pattern.compile("^(.+)\\.kt$"), null, true);
        }

        @Test
        @TestMetadata("as_type_contract.kt")
        public void testAs_type_contract() {
          run("as_type_contract.kt");
        }

        @Test
        @TestMetadata("cond_effects.kt")
        public void testCond_effects() {
          run("cond_effects.kt");
        }

        @Test
        @TestMetadata("contracts_with_receivers.kt")
        public void testContracts_with_receivers() {
          run("contracts_with_receivers.kt");
        }

        @Test
        @TestMetadata("is_type_contract.kt")
        public void testIs_type_contract() {
          run("is_type_contract.kt");
        }

        @Test
        @TestMetadata("list.kt")
        public void testList() {
          run("list.kt");
        }

        @Test
        @TestMetadata("returns_booleans.kt")
        public void testReturns_booleans() {
          run("returns_booleans.kt");
        }

        @Test
        @TestMetadata("returns_not_null.kt")
        public void testReturns_not_null() {
          run("returns_not_null.kt");
        }

        @Test
        @TestMetadata("returns_null.kt")
        public void testReturns_null() {
          run("returns_null.kt");
        }

        @Test
        @TestMetadata("viper_verify.kt")
        public void testViper_verify() {
          run("viper_verify.kt");
        }
      }

      @Nested
      @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive")
      @TestDataPath("$PROJECT_ROOT")
      public class Positive {
        private void run(java.lang.String fileName) {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive/" + fileName);
        }

        @Test
        public void testAllFilesPresentInPositive() {
          KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive"), Pattern.compile("^(.+)\\.kt$"), null, true);
        }

        @Test
        @TestMetadata("as_type_contract.kt")
        public void testAs_type_contract() {
          run("as_type_contract.kt");
        }

        @Test
        @TestMetadata("contracts_with_receivers.kt")
        public void testContracts_with_receivers() {
          run("contracts_with_receivers.kt");
        }

        @Test
        @TestMetadata("is_type_contract.kt")
        public void testIs_type_contract() {
          run("is_type_contract.kt");
        }

        @Test
        @TestMetadata("returns_booleans.kt")
        public void testReturns_booleans() {
          run("returns_booleans.kt");
        }

        @Test
        @TestMetadata("returns_null.kt")
        public void testReturns_null() {
          run("returns_null.kt");
        }

        @Test
        @TestMetadata("simple.kt")
        public void testSimple() {
          run("simple.kt");
        }
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/control_flow")
    @TestDataPath("$PROJECT_ROOT")
    public class Control_flow {
      private void run(java.lang.String fileName) {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/control_flow/" + fileName);
      }

      @Test
      public void testAllFilesPresentInControl_flow() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/control_flow"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("exp_side_effects.kt")
      public void testExp_side_effects() {
        run("exp_side_effects.kt");
      }

      @Test
      @TestMetadata("function_call.kt")
      public void testFunction_call() {
        run("function_call.kt");
      }

      @Test
      @TestMetadata("if.kt")
      public void testIf() {
        run("if.kt");
      }

      @Test
      @TestMetadata("loops.kt")
      public void testLoops() {
        run("loops.kt");
      }

      @Test
      @TestMetadata("non-local-returns.kt")
      public void testNon_local_returns() {
        run("non-local-returns.kt");
      }

      @Test
      @TestMetadata("recursion.kt")
      public void testRecursion() {
        run("recursion.kt");
      }

      @Test
      @TestMetadata("return_break_continue.kt")
      public void testReturn_break_continue() {
        run("return_break_continue.kt");
      }

      @Test
      @TestMetadata("when.kt")
      public void testWhen() {
        run("when.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/inlining")
    @TestDataPath("$PROJECT_ROOT")
    public class Inlining {
      private void run(java.lang.String fileName) {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/" + fileName);
      }

      @Test
      public void testAllFilesPresentInInlining() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/inlining"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("custom_run_functions.kt")
      public void testCustom_run_functions() {
        run("custom_run_functions.kt");
      }

      @Test
      @TestMetadata("inline_returns.kt")
      public void testInline_returns() {
        run("inline_returns.kt");
      }

      @Test
      @TestMetadata("lambdas.kt")
      public void testLambdas() {
        run("lambdas.kt");
      }

      @Test
      @TestMetadata("scoped_receivers.kt")
      public void testScoped_receivers() {
        run("scoped_receivers.kt");
      }

      @Test
      @TestMetadata("viper_casts_while_inlining.kt")
      public void testViper_casts_while_inlining() {
        run("viper_casts_while_inlining.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/negative")
    @TestDataPath("$PROJECT_ROOT")
    public class Negative {
      private void run(java.lang.String fileName) {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/negative/" + fileName);
      }

      @Test
      public void testAllFilesPresentInNegative() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/negative"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("binary_tree.kt")
      public void testBinary_tree() {
        run("binary_tree.kt");
      }

      @Test
      @TestMetadata("linked_list.kt")
      public void testLinked_list() {
        run("linked_list.kt");
      }

      @Test
      @TestMetadata("try_catch.kt")
      public void testTry_catch() {
        run("try_catch.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/operators")
    @TestDataPath("$PROJECT_ROOT")
    public class Operators {
      private void run(java.lang.String fileName) {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/operators/" + fileName);
      }

      @Test
      public void testAllFilesPresentInOperators() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/operators"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("basic.kt")
      public void testBasic() {
        run("basic.kt");
      }

      @Test
      @TestMetadata("elvis.kt")
      public void testElvis() {
        run("elvis.kt");
      }

      @Test
      @TestMetadata("identity_equality.kt")
      public void testIdentity_equality() {
        run("identity_equality.kt");
      }

      @Test
      @TestMetadata("safe_call.kt")
      public void testSafe_call() {
        run("safe_call.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/pure_functions")
    @TestDataPath("$PROJECT_ROOT")
    public class Pure_functions {
      private void run(java.lang.String fileName) {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/pure_functions/" + fileName);
      }

      @Test
      public void testAllFilesPresentInPure_functions() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/pure_functions"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("branching.kt")
      public void testBranching() {
        run("branching.kt");
      }

      @Test
      @TestMetadata("heap_dependent_specifications.kt")
      public void testHeap_dependent_specifications() {
        run("heap_dependent_specifications.kt");
      }

      @Test
      @TestMetadata("literal_returns.kt")
      public void testLiteral_returns() {
        run("literal_returns.kt");
      }

      @Test
      @TestMetadata("local_variables.kt")
      public void testLocal_variables() {
        run("local_variables.kt");
      }

      @Test
      @TestMetadata("operators.kt")
      public void testOperators() {
        run("operators.kt");
      }

      @Test
      @TestMetadata("pure_function_with_heap_dependent_expressions.kt")
      public void testPure_function_with_heap_dependent_expressions() {
        run("pure_function_with_heap_dependent_expressions.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/purity")
    @TestDataPath("$PROJECT_ROOT")
    public class Purity {
      private void run(java.lang.String fileName) {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/purity/" + fileName);
      }

      @Test
      public void testAllFilesPresentInPurity() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/purity"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("assert_statements.kt")
      public void testAssert_statements() {
        run("assert_statements.kt");
      }

      @Test
      @TestMetadata("wrongly_annotated.kt")
      public void testWrongly_annotated() {
        run("wrongly_annotated.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/types")
    @TestDataPath("$PROJECT_ROOT")
    public class Types {
      private void run(java.lang.String fileName) {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/types/" + fileName);
      }

      @Test
      public void testAllFilesPresentInTypes() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/types"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("any.kt")
      public void testAny() {
        run("any.kt");
      }

      @Test
      @TestMetadata("casts.kt")
      public void testCasts() {
        run("casts.kt");
      }

      @Test
      @TestMetadata("generics.kt")
      public void testGenerics() {
        run("generics.kt");
      }

      @Test
      @TestMetadata("nullable.kt")
      public void testNullable() {
        run("nullable.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/user_invariants")
    @TestDataPath("$PROJECT_ROOT")
    public class User_invariants {
      private void run(java.lang.String fileName) {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/" + fileName);
      }

      @Test
      public void testAllFilesPresentInUser_invariants() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/user_invariants"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("and_or_then.kt")
      public void testAnd_or_then() {
        run("and_or_then.kt");
      }

      @Test
      @TestMetadata("empty.kt")
      public void testEmpty() {
        run("empty.kt");
      }

      @Test
      @TestMetadata("exists.kt")
      public void testExists() {
        run("exists.kt");
      }

      @Test
      @TestMetadata("exists_list_get_crash.kt")
      public void testExists_list_get_crash() {
        run("exists_list_get_crash.kt");
      }

      @Test
      @TestMetadata("factorial.kt")
      public void testFactorial() {
        run("factorial.kt");
      }

      @Test
      @TestMetadata("forall_with_triggers.kt")
      public void testForall_with_triggers() {
        run("forall_with_triggers.kt");
      }

      @Test
      @TestMetadata("loops.kt")
      public void testLoops() {
        run("loops.kt");
      }

      @Test
      @TestMetadata("simple_forall.kt")
      public void testSimple_forall() {
        run("simple_forall.kt");
      }

      @Test
      @TestMetadata("simple_postcondition.kt")
      public void testSimple_postcondition() {
        run("simple_postcondition.kt");
      }

      @Test
      @TestMetadata("simple_precondition.kt")
      public void testSimple_precondition() {
        run("simple_precondition.kt");
      }

      @Test
      @TestMetadata("string_iterations.kt")
      public void testString_iterations() {
        run("string_iterations.kt");
      }

      @Test
      @TestMetadata("strings_in_conditions.kt")
      public void testStrings_in_conditions() {
        run("strings_in_conditions.kt");
      }

      @Test
      @TestMetadata("sum_of_1_to_n.kt")
      public void testSum_of_1_to_n() {
        run("sum_of_1_to_n.kt");
      }
    }
  }
}
